### ISSUE TITLE
Location tracked message when tracking is allowed 

### ISSUE THREAD

**Issue by ellemindwave** [LDMW/cms#183]
- [x] message to appear that lets the user know we are tracking their location
- [x] something along the lines of 'we are using your location to make your search results more tailored to you' ... 
- [x] would appear below the beta banner and then disappear?

---- UPDATE ----

- [x] Only show this banner once with the same format as the cookie banner

**Comment by Cleop** [comment]
@ellemindwave would this message overlap the hero image? or would it have a background (like the beta banner does)?

How does it disappear? By clicking an 'X'?

![image](https://user-images.githubusercontent.com/16775804/29969800-bb08eab0-8f19-11e7-9a78-c135e7a18240.png)

**Comment by ellemindwave** [comment]
@Cleop This would be a banner that would be at the very top of the page, above the beta banner. It can be closed by clicking an 'X' or it will automatically disappear after 5 seconds. Whichever is easiest to implement.

The banner should be dark blue please for now. 
@indiamindwave24 unless you strongly advise against it, but the UI will be changing soon anyway?
