### ISSUE TITLE
Migrate from Phoenix to Wagtail

### ISSUE THREAD

**Issue by samhstn** [LDMW/cms#50]
Moved over from this issue: https://github.com/LDMW/app/issues/483

Overall high level plan:
- [x] Consider what rearchitechuring some of the ways we are storing our data in wagtail #51
- [x] Copy data to new wagtail instance
- [x] Transfer over templates #52
- [x] Set up non static routes in python
  - [ ] ~~Set up google sheets logic in python~~ #54 (storing data in admin view instead)
  - [x] Set up search logic in python (consider elastic search) #53 
  - [x] Storing likes data in our database #56 
  - [x] Storing all data sent to spreadsheet with python #56 
- [x] Write python tests #55
- [x] Relocate all js and css files #60
- [x] Resetup deployment and ci
- [x] Other static pages #65
- [x] Google Analytics #64 
(we will add to this list as tasks come up)

**Comment by nelsonic** [comment]
@dwylbot[bot] don't _worry_ about it, it's an `epic` so estimation is difficult. see: https://github.com/dwyl/dwylbot/issues/138
(_the checklist items in the `epic` will made into separate issues which will in turn be estimated_)

**Comment by samhstn** [comment]
We may not need google sheet logic at all as wagtail offers collecting all of this data in the admin view

**Comment by nelsonic** [comment]
Indeed. (_as mentioned at the time Google Sheets were proposed_...) 👍

**Comment by nelsonic** [comment]
@shouston3 having _two_ v. similar issues:
![image](https://user-images.githubusercontent.com/194400/28377998-8ed6e932-6ca6-11e7-9345-59bf5995f16b.png)

_could_ be confusing to stakeholders, do you think we could close (_and re-direct_) one of them?

**Comment by samhstn** [comment]
Closed https://github.com/LDMW/app/issues/483 in favour of this one

**Comment by samhstn** [comment]
Seems all addressed 👍
