### ISSUE TITLE
Change medium screen sizes to mobile view

### ISSUE THREAD

**Issue by katbow** [LDMW/cms#549]
I would like medium size devices (up to iPad portrait) to use content width the same as mobile devices. 

**Details**

On iPad, the boxes (such as those on the resource list view or home page topic cards) should go across the full length of the screen. This comes out of #505 and should help with some of the specific issues listed there.
* https://github.com/mindwaveventures/cms/issues/505#issuecomment-333882144
  - [x] `Order by` should remain on one line #528 
  - [x] Pros and cons should not be as 'squished' - they should take up more horizontal space and less vertical space.
  - [x] Previous/next question buttons should not overlap tags (see #519)
  - [x] Align buttons in questionnaires https://github.com/mindwaveventures/cms/issues/505#issuecomment-333487476
 

@ellemindwave Can you review and prioritise please?

**Comment by katbow** [comment]
Pros and cons so far:
![image](https://user-images.githubusercontent.com/1287388/31285563-8985a95a-aab3-11e7-901e-272eb61168fc.png)
