### ISSUE TITLE
Homepage Template

### ISSUE THREAD

**Issue by Danwhy** [LDMW/cms#57]
part of #52 
Specifics for reimplementing the homepage template:

- [x] Homepage
  - [x] Search Bars
    - [x] Hook up Search bars #53
    - [x] Make tags and search work together
  - [x] Resources
    - [x] Basic rendering of all content
    - [x] Make clicking tags filter by tag
    - [x] Like/Feedback (depends on saving like data in db #56)
      - [x] Like counts
      - [x] Liked state
      - [x] Clicking like/dislike works
      - [x] Sending Feedback works
      - [x] Icons
    - [x] Pros/cons hidden on mobile by default
    - [x] Making sure all google analytics data for resources is implemented  (data-urls etc) #64 
  - [x] Sidebar
    - [x] Content
    - [x] Tag filter functionality
  - [x] Alpha/Beta box
  - [x] Banner
  - [x] Feedback boxes (depends on #62)
  - [x] Crisis/Assessment banners
